### ISSUE TITLE
ls.getStoichiometryMatrix() does work?

### ISSUE THREAD

**Issue by hsauro** [yosefmaru/Libstructural#1]
If I run

import structural

ls = structural.LibStructural.getInstance()
matrix = [[  1, -1, -1], [  0, -1,  1], [  0,  1, -1]] # matrix can be a numpy 2d array
ls.loadStoichiometryMatrix(matrix)
print ls.getStoichiometryMatrix() 

I get the error message:

Traceback (most recent call last):

  File "<ipython-input-8-27923c2c1fa0>", line 1, in <module>
    x = ls.getStoichiometryMatrix()

  File "C:\Tellurium-Winpython\python-2.7.13.amd64\lib\site-packages\structural\structural.py", line 1018, in getStoichiometryMatrix
    return self._my_getStoichiometryMatrix().toNumpy()

AttributeError: 'NoneType' object has no attribute 'toNumpy'

**Comment by yosefmaru** [comment]
It seems like ls.getStoichiometryMatrix() doesn't run  analyzeWithQR() by default. So you have to run ls.analyzeWithQR() right after loading the stoichiometry matrix. You don't have to run analyzeWithQR after loading SBML string or file.

**Comment by hsauro** [comment]
I should close this I updated the code to fix this.

Herbert
