### ISSUE TITLE
Allow structural to be instanciated using ls = structural.LibStructural()

### ISSUE THREAD

**Issue by hsauro** [yosefmaru/Libstructural#7]
When uses instanciate structural, use the syntax:

ls = structural.LibStructural()

instead of the current approach:

ls = structural.LibStructural.getInstance()

This would match the way its done with roadrunner.

**Comment by yosefmaru** [comment]
I found out that you can actually instantiate using structural.LibStructural(). No need to run structural.LibStructural.getInstance().
